---
esphome:
  name: esphome-web-938e59
  friendly_name: Test ESP
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

sensor:
  - platform: homeassistant
    id: outside_temp
    entity_id: sensor.newcastle_nobbys_temp
  - platform: homeassistant
    id: current_temperature
    entity_id: climate.living_room_aircon
    attribute: current_temperature
  - platform: homeassistant
    id: current_target
    entity_id: climate.living_room_aircon
    attribute: temperature
  - platform: homeassistant
    id: temphigh
    entity_id: sensor.cooks_hill_temp_max_0
  - platform: homeassistant
    id: templow
    entity_id: sensor.cooks_hill_temp_min_0

text_sensor:
  - platform: homeassistant
    id: aircon_state
    entity_id: climate.living_room_aircon

display:
  - platform: lcd_gpio
    dimensions: 16x2
    data_pins:
      - GPIO16
      - GPIO5
      - GPIO4
      - GPIO0
    enable_pin: GPIO12
    rs_pin: GPIO14
    user_characters:
      - position: 0
        data:
          - 0b00100
          - 0b01010
          - 0b00100
          - 0b00000
          - 0b00000
          - 0b00000
          - 0b00000
          - 0b00000
      - position: 1
        data:
          - 0b00100
          - 0b00100
          - 0b00100
          - 0b00100
          - 0b00100
          - 0b00100
          - 0b00100
          - 0b00100
      - position: 2
        data:
          - 0b00000
          - 0b00000
          - 0b00000
          - 0b00000
          - 0b00000
          - 0b11000
          - 0b01000
          - 0b10000
    lambda: |-
      it.printf(0, 0, "Home\x02 %3.1f", id(current_temperature).state);
      it.printf(0, 1, "%3.1f C %2.0f - %2.0f C", id(outside_temp).state, id(templow).state, id(temphigh).state);
      it.printf(4, 1, "\x08");
      it.printf(6, 1, "\x02");
      it.printf(14, 1, "\x08");
      if (id(aircon_state).state != "off") {
        it.printf(11, 0, "-> %2.0f", id(current_target).state);
      }

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
